---
name: Publish to Puppet Forge

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build and publish module

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: bundle install --jobs 4

      - name: Run tests before publishing
        run: bundle exec rake spec

      - name: Publish to Puppet Forge
        uses: barnumbirr/action-forge-publish@v2.15.0
        env:
          FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
          REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
